### ISSUE TITLE
Uncaught TypeError: t.extGetItemProps is not a function

### ISSUE THREAD

**Issue by ethangodt** [reasonml-community/bs-downshift#8]
```
react-dom.development.js:9627 The above error occurred in the <Downshift> component:
    in Downshift (created by GroupsList)
    in div (created by GroupsList)
    in GroupsList (created by Popup)
    in div (created by ViewWrapper)
    in ViewWrapper (created by Popup)
    in div (created by Popup)
    in Popup (created by App)
    in App

Uncaught TypeError: t.extGetItemProps is not a function
    at Array.getItemProps (Downshift.bs.js:13)
    at eval (GroupsList.bs.js:113)
    at Object._2 (curry.js:127)
    at Object.mapi (array.js:122)
    at eval (GroupsList.bs.js:111)
    at Downshift.render (downshift.esm.js:856)
    at finishClassComponent (react-dom.development.js:8377)
    at updateClassComponent (react-dom.development.js:8345)
    at beginWork (react-dom.development.js:8966)
    at performUnitOfWork (react-dom.development.js:11798)
```

It can't seem to find https://github.com/reasonml-community/bs-downshift/blob/07209b9b720eaf22af1824a34b91d0be2c19275e/src/Downshift.re#L104

When I look at the `t` argument in the console it contains these methods:

[
  "getRootProps",
  "getButtonProps",
  "getLabelProps",
  "getInputProps",
  "getItemProps",
  "reset",
  "openMenu",
  "closeMenu",
  "toggleMenu",
  "selectItem",
  "selectItemAtIndex",
  "selectHighlightedItem",
  "setHighlightedIndex",
  "clearSelection",
  "clearItems",
  "setItemCount",
  "unsetItemCount",
  "itemToString",
  "id",
  "highlightedIndex",
  "inputValue",
  "isOpen",
  "selectedItem"
]

**Comment by ethangodt** [comment]
This happens even when I copy https://github.com/reasonml-community/bs-downshift/blob/master/examples/reason_downshift.re#L7 exactly.

**Comment by boyswan** [comment]
Same issue..

**Comment by rabet** [comment]
Same issue here :(
